// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKJkokQ8LNxwH5OkiXD1J5g69C05CjPk8',
    appId: '1:1025267853843:web:ea05e5d60ef460cd456de6',
    messagingSenderId: '1025267853843',
    projectId: 'jumachu123-a4915',
    authDomain: 'jumachu123-a4915.firebaseapp.com',
    storageBucket: 'jumachu123-a4915.appspot.com',
    measurementId: 'G-87QWVYQDXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASNFzR_HAswMcONLESFJB_sXBC4ePX2bo',
    appId: '1:1025267853843:android:91feb9d9e029f1b7456de6',
    messagingSenderId: '1025267853843',
    projectId: 'jumachu123-a4915',
    storageBucket: 'jumachu123-a4915.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoUy-f1SjWm41Tc70_Aj4PBDCp6MxbURA',
    appId: '1:1025267853843:ios:d20cae19cfda9a0e456de6',
    messagingSenderId: '1025267853843',
    projectId: 'jumachu123-a4915',
    storageBucket: 'jumachu123-a4915.appspot.com',
    iosBundleId: 'com.example.gdscFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoUy-f1SjWm41Tc70_Aj4PBDCp6MxbURA',
    appId: '1:1025267853843:ios:efc03c51468d2d18456de6',
    messagingSenderId: '1025267853843',
    projectId: 'jumachu123-a4915',
    storageBucket: 'jumachu123-a4915.appspot.com',
    iosBundleId: 'com.example.gdscFirebase.RunnerTests',
  );
}
